FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir psycopg2-binary python-dotenv sqlalchemy sqlalchemy-utils passlib

# Copy initialization script
COPY initialize_database.py .

# Run the initialization script
CMD ["python", "initialize_database.py"]
