version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bitebase
    ports:
      - "5432:5432"
    networks:
      - bitebase-network
    restart: always

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - bitebase-network
    restart: always

networks:
  bitebase-network:

volumes:
  postgres_data:
