services:
  - type: web
    name: bitebase-app
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_APP_ENV
        value: production
