name = "bitebase-app"
compatibility_date = "2023-10-30"

# Specify the build output directory for Pages
pages_build_output_dir = "dist"

# Environment variables
[vars]
ENVIRONMENT = "production"
VITE_APP_ENV = "production"
VITE_API_URL = "https://bitebase-chatbot.bitebase.workers.dev/api/v1"
VITE_CLOUDFLARE_AI_TOKEN = "dIPwmSfU475UYmZaKivaQ-fhvt_jh6W8QaKxJ4d5"
