name: Deploy Backend to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'cloudflare/backend-worker.js'
      - 'cloudflare/backend-wrangler.toml'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Wrangler
        run: npm install -g wrangler
      
      - name: Deploy to Cloudflare Workers
        run: |
          cd cloudflare
          wrangler deploy backend-worker.js --config backend-wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
